import tokenize from "./src/lex.js";
import parse from "./src/parser.js";
import { readFileSync, writeFileSync } from "fs";
import { run_command } from "./src/utils.js";
import process from "process";
import { ArgumentParser } from "argparse";

const parser = new ArgumentParser({
    description: "The Official Gerbile Compiler OwO"
});
parser.add_argument("-v", "--version", { action: "version", version: "1.0.0" });
parser.add_argument("-t", "--show-tokens", { action: "store_true", dest: "tokens", help: "Output tokens generated by lexer"});
parser.add_argument("-a", "--show-asm", { action: "store_true", dest: "asm", help: "Output assembly generated by parser"});
parser.add_argument("-r", "--run", { action: "store_true", dest: "run", help: "Run executable after compilation"});
parser.add_argument("FILE", {help: "Path to source file"});
let args = parser.parse_args();

let text = readFileSync(args.FILE, {encoding:"utf8", flag:"r"}, (err, data) => {
	if (err) console.error(err);
})

let toks = tokenize(text);
// console.log(toks);
if (args.tokens) console.log(toks);
let asm = parse(toks);
if (args.asm) console.log(asm);

writeFileSync("./test.asm", asm, (err) => {
	if (err) console.error(err);
});

let exit_code = run_command("fasm ./test.asm");
if (args.run && exit_code === 0) {
    run_command("./test", {code: true});
}
